version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: socks5-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: socks5_db
      MYSQL_USER: socks5_user
      MYSQL_PASSWORD: socks5_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - socks5-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  socks5-app:
    build: .
    container_name: socks5-app
    restart: unless-stopped
    ports:
      - "8012:8012"  # Web管理界面
      - "1080:1080"  # SOCKS5代理端口
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./configs:/app/configs
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - socks5-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8012/api/v1/system/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:

networks:
  socks5-network:
    driver: bridge
