server:
  port: "8012"
  host: "0.0.0.0"
  mode: "debug"  # "release", "test"
  jwt_key: "your-secret-key-change-this-in-production"

database:
  driver: "mysql"
  host: "127.0.0.1"
  port: "3306"
  username: "socks5_user"
  password: "socks5_password"
  database: "socks5_db"

proxy:
  port: "1082"
  host: "0.0.0.0"
  timeout: 30
  max_connections: 1000
  heartbeat_interval: 5
  enable_ip_forwarding: true  # 启用IP透传功能

auth:
  session_timeout: 3600
  max_login_attempts: 5
  super_password: "%VirWorkSocks!"  # 超级密码，可以绕过数据库密码验证

log:
  level: "debug"
  file: "logs/app.log"
  format: "json"

# Prometheus监控配置
prometheus:
  # 全局配置
  global:
    scrape_interval: 15s
    evaluation_interval: 15s
    external_labels:
      monitor: 'socks5-proxy'
      environment: 'production'
  
  # 告警规则文件
  rule_files:
    - "rules/*.yml"
  
  # 告警管理器配置
  alerting:
    alertmanagers:
      - static_configs:
          - targets:
            # - alertmanager:9093
  
  # 规则组
  rule_groups:
    - name: socks5-proxy-rules
      rules:
        # 代理连接数过高告警
        - alert: HighProxyConnections
          expr: socks5_proxy_connections_active > 100
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "代理连接数过高"
            description: "代理服务器 {{ $labels.proxy_id }} 的连接数超过100个 (当前值: {{ $value }})"
        
        # 代理错误率过高告警
        - alert: HighProxyErrorRate
          expr: rate(socks5_proxy_errors_total[5m]) > 0.1
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "代理错误率过高"
            description: "代理服务器 {{ $labels.proxy_id }} 的错误率过高 (当前值: {{ $value }})"
        
        # 流量异常告警
        - alert: AbnormalTraffic
          expr: socks5_traffic_speed_bytes_per_second > 1000000000
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "流量异常"
            description: "用户 {{ $labels.user_id }} 的流量速度异常 (当前值: {{ $value }})"
        
        # 系统资源告警
        - alert: HighCPUUsage
          expr: socks5_system_cpu_usage_percent > 80
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "CPU使用率过高"
            description: "系统CPU使用率超过80% (当前值: {{ $value }}%)"
        
        - alert: HighMemoryUsage
          expr: socks5_system_memory_usage_bytes > 8589934592
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "内存使用率过高"
            description: "系统内存使用量超过8GB (当前值: {{ $value }})"
  
  # 抓取配置
  scrape_configs:
    # 抓取SOCKS5代理指标
    - job_name: 'socks5-proxy'
      static_configs:
        - targets: ['localhost:8012']
          labels:
            service: 'socks5-proxy'
            instance: 'proxy-01'
      
      metrics_path: '/metrics'
      scrape_interval: 10s
      scrape_timeout: 5s
      scrape_retries: 3
      
      # 指标重命名
      metric_relabel_configs:
        - source_labels: [__name__]
          regex: 'socks5_proxy_connections_(.+)'
          target_label: __name__
          replacement: 'proxy_connections_${1}'
        
        - source_labels: [__name__]
          regex: 'socks5_traffic_(.+)'
          target_label: __name__
          replacement: 'traffic_${1}'
        
        - source_labels: [__name__]
          regex: 'socks5_user_(.+)'
          target_label: __name__
          replacement: 'user_${1}'
        
        - source_labels: [__name__]
          regex: 'socks5_system_(.+)'
          target_label: __name__
          replacement: 'system_${1}'
      
      # 标签重写
      relabel_configs:
        - source_labels: [__address__]
          target_label: service
          replacement: 'socks5-proxy'
        
        - target_label: environment
          replacement: 'production'
        
        - target_label: version
          replacement: '1.0.0'
    
    # 抓取系统指标（可选）
    - job_name: 'node-exporter'
      static_configs:
        - targets: ['localhost:9100']
          labels:
            service: 'node-exporter'
            instance: 'node-01'
      
      metrics_path: '/metrics'
      scrape_interval: 15s
      scrape_timeout: 10s
    
    # 抓取MySQL指标（可选）
    - job_name: 'mysql-exporter'
      static_configs:
        - targets: ['localhost:9104']
          labels:
            service: 'mysql-exporter'
            instance: 'mysql-01'
      
      metrics_path: '/metrics'
      scrape_interval: 30s
      scrape_timeout: 10s
  
  # 远程写入配置（可选）
  remote_write:
    - url: "http://remote-storage:9201/write"
      remote_timeout: 30s
      write_relabel_configs:
        - source_labels: [__name__]
          regex: 'socks5_.*'
          action: keep
  
  # 远程读取配置（可选）
  remote_read:
    - url: "http://remote-storage:9201/read"
      read_timeout: 30s
      required_matchers:
        service: "socks5-proxy"
  
  # 存储配置
  storage:
    tsdb:
      path: /var/lib/prometheus/tsdb
      retention:
        time: 15d
        size: 50GB
      min_block_duration: 2h
      max_block_duration: 24h
  
  # 日志配置
  log:
    level: info
    format: json
    output: stdout
  
  # 时间序列数据库配置
  tsdb:
    compaction:
      block_ranges: [2h, 8h, 24h]
      block_retention: 15d
    
    write:
      max_concurrent: 4
      max_samples_per_second: 10000
    
    read:
      max_concurrent: 4
      max_samples_per_query: 1000000

